bla = {
	{
		bufnr = 2,
		changed = 1,
		changedtick = 7,
		hidden = 0,
		lastused = 1680614902,
		linecount = 70,
		listed = 1,
		lnum = 8,
		loaded = 1,
		name = "/Users/chrisgrieser/Library/Mobile Documents/com~apple~CloudDocs/Repos/nvim-early-retirement/lua/early-retirement.lua",
		signs = {
			{
				group = "vim.diagnostic.vim.lsp.lua_ls.1",
				id = 12,
				lnum = 3,
				name = "DiagnosticSignHint",
				priority = 10,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 3,
				lnum = 3,
				name = "GitSignsChange",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 20,
				lnum = 20,
				name = "GitSignsAdd",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 23,
				lnum = 23,
				name = "GitSignsChange",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 24,
				lnum = 24,
				name = "GitSignsAdd",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 25,
				lnum = 25,
				name = "GitSignsAdd",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 26,
				lnum = 26,
				name = "GitSignsAdd",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 27,
				lnum = 27,
				name = "GitSignsAdd",
				priority = 6,
			},
			{
				group = "vim.diagnostic.vim.lsp.lua_ls.1",
				id = 14,
				lnum = 28,
				name = "DiagnosticSignWarn",
				priority = 10,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 28,
				lnum = 28,
				name = "GitSignsAdd",
				priority = 6,
			},
			{
				group = "vim.diagnostic.vim.lsp.lua_ls.1",
				id = 13,
				lnum = 62,
				name = "DiagnosticSignHint",
				priority = 10,
			},
		},
		variables = {
			__indent_blankline_active = true,
			__indent_blankline_ranges = {
				["0"] = { { 0, 40 } },
			},
			autopairs_keymaps = { "{", "}", "`", "[", "]", "<", "(", ")", "'", '"' },
			changedtick = 7,
			cur_branch = "main",
			did_ftplugin = 1,
			did_indent = 1,
			gitsigns_head = "main",
			gitsigns_status = "+8 ~3",
			gitsigns_status_dict = {
				added = 8,
				changed = 3,
				gitdir = "/Users/chrisgrieser/Library/Mobile Documents/com~apple~CloudDocs/Repos/nvim-early-retirement/.git",
				head = "main",
				removed = 0,
				root = "/Users/chrisgrieser/Library/Mobile Documents/com~apple~CloudDocs/Repos/nvim-early-retirement",
			},
			harpoonMark = "",
			match_ignorecase = 0,
			match_words = "\\<\\%(do\\|function\\|if\\)\\>:\\<\\%(return\\|else\\|elseif\\)\\>:\\<end\\>,\\<repeat\\>:\\<until\\>,\\%(--\\)\\=\\[\\(=*\\)\\[:]\\1]",
			navic_awaiting_lsp_response = true,
			navic_client_id = 1,
			navic_client_name = "lua_ls",
			["nvim-autopairs"] = 1,
			timeOpened = 1680614686,
			ts_highlight = true,
			undo_ftplugin = "setlocal cms< com< def< fo< sua< | unlet! b:match_words b:match_ignorecase",
			undo_indent = "setlocal autoindent< indentexpr< indentkeys<",
		},
		windows = { 1000 },
	},
	{
		bufnr = 12,
		changed = 0,
		changedtick = 11,
		hidden = 1,
		lastused = 1680614876,
		linecount = 189,
		listed = 1,
		lnum = 123,
		loaded = 1,
		name = "/Users/chrisgrieser/Library/Mobile Documents/com~apple~CloudDocs/Repos/nvim-early-retirement/lua/Untitled.lua",
		signs = {
			{
				group = "vim.diagnostic.vim.lsp.lua_ls.1",
				id = 5,
				lnum = 1,
				name = "DiagnosticSignInfo",
				priority = 10,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 1,
				lnum = 1,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 2,
				lnum = 2,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 3,
				lnum = 3,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 4,
				lnum = 4,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 5,
				lnum = 5,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 6,
				lnum = 6,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 7,
				lnum = 7,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 8,
				lnum = 8,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 9,
				lnum = 9,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 10,
				lnum = 10,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 11,
				lnum = 11,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 12,
				lnum = 12,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 13,
				lnum = 13,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 14,
				lnum = 14,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 15,
				lnum = 15,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 16,
				lnum = 16,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 17,
				lnum = 17,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 18,
				lnum = 18,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 19,
				lnum = 19,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 20,
				lnum = 20,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 21,
				lnum = 21,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 22,
				lnum = 22,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 23,
				lnum = 23,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 24,
				lnum = 24,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 25,
				lnum = 25,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 26,
				lnum = 26,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 27,
				lnum = 27,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 28,
				lnum = 28,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 29,
				lnum = 29,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 30,
				lnum = 30,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 31,
				lnum = 31,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 32,
				lnum = 32,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 33,
				lnum = 33,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 34,
				lnum = 34,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 35,
				lnum = 35,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 36,
				lnum = 36,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 37,
				lnum = 37,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 38,
				lnum = 38,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 39,
				lnum = 39,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 40,
				lnum = 40,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 41,
				lnum = 41,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 42,
				lnum = 42,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 43,
				lnum = 43,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 44,
				lnum = 44,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 45,
				lnum = 45,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 46,
				lnum = 46,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 47,
				lnum = 47,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 48,
				lnum = 48,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 49,
				lnum = 49,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 50,
				lnum = 50,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 51,
				lnum = 51,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 52,
				lnum = 52,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 53,
				lnum = 53,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 54,
				lnum = 54,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 55,
				lnum = 55,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 56,
				lnum = 56,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 57,
				lnum = 57,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 58,
				lnum = 58,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 59,
				lnum = 59,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 60,
				lnum = 60,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 61,
				lnum = 61,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 62,
				lnum = 62,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 63,
				lnum = 63,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 64,
				lnum = 64,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 65,
				lnum = 65,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 66,
				lnum = 66,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 67,
				lnum = 67,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 68,
				lnum = 68,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 69,
				lnum = 69,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 70,
				lnum = 70,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 71,
				lnum = 71,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 72,
				lnum = 72,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 73,
				lnum = 73,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 74,
				lnum = 74,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 75,
				lnum = 75,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 76,
				lnum = 76,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 77,
				lnum = 77,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 78,
				lnum = 78,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 79,
				lnum = 79,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 80,
				lnum = 80,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 81,
				lnum = 81,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 82,
				lnum = 82,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 83,
				lnum = 83,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 84,
				lnum = 84,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 85,
				lnum = 85,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 86,
				lnum = 86,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 87,
				lnum = 87,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 88,
				lnum = 88,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 89,
				lnum = 89,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 90,
				lnum = 90,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 91,
				lnum = 91,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 92,
				lnum = 92,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 93,
				lnum = 93,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 94,
				lnum = 94,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 95,
				lnum = 95,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 96,
				lnum = 96,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 97,
				lnum = 97,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 98,
				lnum = 98,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 99,
				lnum = 99,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 100,
				lnum = 100,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 101,
				lnum = 101,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 102,
				lnum = 102,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 103,
				lnum = 103,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 104,
				lnum = 104,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 105,
				lnum = 105,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 106,
				lnum = 106,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 107,
				lnum = 107,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 108,
				lnum = 108,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 109,
				lnum = 109,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 110,
				lnum = 110,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 111,
				lnum = 111,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 112,
				lnum = 112,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 113,
				lnum = 113,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 114,
				lnum = 114,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 115,
				lnum = 115,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 116,
				lnum = 116,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 117,
				lnum = 117,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 118,
				lnum = 118,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "vim.diagnostic.NULL_LS_SOURCE_1",
				id = 1,
				lnum = 119,
				name = "DiagnosticSignWarn",
				priority = 10,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 119,
				lnum = 119,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 120,
				lnum = 120,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 121,
				lnum = 121,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 122,
				lnum = 122,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 123,
				lnum = 123,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 124,
				lnum = 124,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 125,
				lnum = 125,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 126,
				lnum = 126,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 127,
				lnum = 127,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 128,
				lnum = 128,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 129,
				lnum = 129,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 130,
				lnum = 130,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 131,
				lnum = 131,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 132,
				lnum = 132,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 133,
				lnum = 133,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 134,
				lnum = 134,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 135,
				lnum = 135,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 136,
				lnum = 136,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 137,
				lnum = 137,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 138,
				lnum = 138,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 139,
				lnum = 139,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 140,
				lnum = 140,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 141,
				lnum = 141,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 142,
				lnum = 142,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 143,
				lnum = 143,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 144,
				lnum = 144,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 145,
				lnum = 145,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 146,
				lnum = 146,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 147,
				lnum = 147,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 148,
				lnum = 148,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 149,
				lnum = 149,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 150,
				lnum = 150,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 151,
				lnum = 151,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 152,
				lnum = 152,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 153,
				lnum = 153,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 154,
				lnum = 154,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 155,
				lnum = 155,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 156,
				lnum = 156,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 157,
				lnum = 157,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 158,
				lnum = 158,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 159,
				lnum = 159,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 160,
				lnum = 160,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 161,
				lnum = 161,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 162,
				lnum = 162,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 163,
				lnum = 163,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 164,
				lnum = 164,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 165,
				lnum = 165,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 166,
				lnum = 166,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 167,
				lnum = 167,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 168,
				lnum = 168,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 169,
				lnum = 169,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 170,
				lnum = 170,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 171,
				lnum = 171,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 172,
				lnum = 172,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 173,
				lnum = 173,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 174,
				lnum = 174,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 175,
				lnum = 175,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 176,
				lnum = 176,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 177,
				lnum = 177,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 178,
				lnum = 178,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 179,
				lnum = 179,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 180,
				lnum = 180,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 181,
				lnum = 181,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 182,
				lnum = 182,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 183,
				lnum = 183,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 184,
				lnum = 184,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 185,
				lnum = 185,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 186,
				lnum = 186,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 187,
				lnum = 187,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 188,
				lnum = 188,
				name = "GitSignsUntracked",
				priority = 6,
			},
			{
				group = "gitsigns_vimfn_signs_",
				id = 189,
				lnum = 189,
				name = "GitSignsUntracked",
				priority = 6,
			},
		},
		variables = {
			__indent_blankline_active = true,
			__indent_blankline_ranges = {
				["0"] = { { 0, 150 } },
			},
			autopairs_keymaps = { "{", "}", "`", "[", "]", "<", "(", ")", "'", '"' },
			changedtick = 11,
			did_ftplugin = 1,
			did_indent = 1,
			gitsigns_head = "main",
			gitsigns_status = "+189",
			gitsigns_status_dict = {
				added = 189,
				changed = 0,
				gitdir = "/Users/chrisgrieser/Library/Mobile Documents/com~apple~CloudDocs/Repos/nvim-early-retirement/.git",
				head = "main",
				removed = 0,
				root = "/Users/chrisgrieser/Library/Mobile Documents/com~apple~CloudDocs/Repos/nvim-early-retirement",
			},
			match_ignorecase = 0,
			match_words = "\\<\\%(do\\|function\\|if\\)\\>:\\<\\%(return\\|else\\|elseif\\)\\>:\\<end\\>,\\<repeat\\>:\\<until\\>,\\%(--\\)\\=\\[\\(=*\\)\\[:]\\1]",
			navic_awaiting_lsp_response = true,
			navic_client_id = 1,
			navic_client_name = "lua_ls",
			["nvim-autopairs"] = 1,
			ts_highlight = true,
			undo_ftplugin = "setlocal cms< com< def< fo< sua< | unlet! b:match_words b:match_ignorecase",
			undo_indent = "setlocal autoindent< indentexpr< indentkeys<",
		},
		windows = {},
	},
}
